process.env.NODE_ENV='test';
process.env.USE_LOCAL_STORAGE='1';
process.env.LOCAL_STORAGE_DIR='/tmp/design-thinking-v11-enhanced-smoke';
process.env.EXPERIMENT_RUN_ID=`smoke-${Date.now()}`;
process.env.COZE_MOCK='1';
process.env.COZE_FREE_BOT_ID='free-bot';
process.env.COZE_SUPPORTED_BOT_ID='supported-bot';
const { researchService } = await import('../src/services/researchService.js');
const { getSessionConfig, aiVariantFor } = await import('../src/config/researchConfig.js');
const { cozeService } = await import('../src/services/cozeService.js');
await researchService.createParticipant('S01',{grade:'7',condition:'unassigned'});
let r=await researchService.ensureStarted('S01','W1'); if(!r.started_at) throw new Error('W1 not started');
await researchService.markAiOpened('S01','W1'); await researchService.markFirstUserMessage('S01','W1');
r=await researchService.getSessionRecord('S01','W1'); if(r.first_user_message_latency_seconds==null) throw new Error('latency missing');
await researchService.appendMessage('S01','W1',{role:'user',content:'请看看我的草图哪里可以改',content_type:'text+image',message_has_image:true,attachments:[{type:'image',file_name:'chat_test.jpg',file_path:'uploads/S01/W1/chat/chat_test.jpg'}]});
const msgs=await researchService.getMessages('S01','W1'); if(!msgs[0]?.message_has_image||msgs[0]?.attachments?.length!==1) throw new Error('image message metadata missing');
await researchService.setParticipantMeta('S01',{condition:'A'});
if(aiVariantFor({session:getSessionConfig('W4'),condition:'A',isTest:false})!=='supported') throw new Error('A routing failed');
if(aiVariantFor({session:getSessionConfig('W4'),condition:'B',isTest:false})!=='free') throw new Error('B routing failed');
if(aiVariantFor({session:getSessionConfig('W10'),condition:'A',isTest:false})!=='free') throw new Error('transfer routing failed');
const mm=cozeService.buildAdditionalMessage('看看这张图',{fileId:'112233'});
if(mm.content_type!=='object_string'||!mm.content.includes('image')) throw new Error('multimodal Coze message failed');
const reset=await researchService.archiveAndResetSession('S01','W1',{reason:'smoke_reset'});
if(!reset.archived_previous) throw new Error('reset archive missing');
r=await researchService.getSessionRecord('S01','W1');
if(r.started_at||r.ai_used||Object.keys(r.artifacts||{}).length) throw new Error('session reset failed');
const archives=await researchService.listResetArchives();
if(!archives.length) throw new Error('reset archive list missing');
console.log('SMOKE OK: timing + image metadata + multimodal payload + A/B/transfer routing + safe reset passed.');
