process.env.NODE_ENV='test';
process.env.USE_LOCAL_STORAGE='1';
process.env.LOCAL_STORAGE_DIR='/tmp/design-thinking-v11-enhanced-smoke';
process.env.EXPERIMENT_RUN_ID=`smoke-${Date.now()}`;
process.env.COZE_MOCK='1';
process.env.COZE_FREE_BOT_ID='free-bot';
process.env.COZE_SUPPORTED_BOT_ID='supported-bot';
const { researchService } = await import('../src/services/researchService.js');
const { getSessionConfig, aiVariantFor } = await import('../src/config/researchConfig.js');
const { cozeService } = await import('../src/services/cozeService.js');
const { storageService } = await import('../src/services/storageService.js');
await researchService.createParticipant('S01',{grade:'7',condition:'unassigned'});
await researchService.setParticipantMeta('S01',{login_name:'张三'});
const p1=await researchService.getParticipant('S01');
if(!p1.login_name_hash||p1.login_name_hash==='张三'||Object.prototype.hasOwnProperty.call(p1,'login_name')) throw new Error('privacy-safe login name hash missing');
let r=await researchService.ensureStarted('S01','W1'); if(!r.started_at) throw new Error('W1 not started');
await researchService.markAiOpened('S01','W1'); await researchService.markFirstUserMessage('S01','W1');
r=await researchService.getSessionRecord('S01','W1'); if(r.first_user_message_latency_seconds==null) throw new Error('latency missing');
await researchService.appendMessage('S01','W1',{role:'user',content:'请看看我的草图哪里可以改',content_type:'text+image',message_has_image:true,attachments:[{type:'image',file_name:'chat_test.jpg',file_path:'uploads/S01/W1/chat/chat_test.jpg'}],interaction_id:'smoke-i1',client_sent_at:'2026-09-22T00:00:00.000Z',server_received_at:'2026-09-22T00:00:00.100Z',ai_request_started_at:'2026-09-22T00:00:00.120Z',ai_response_received_at:'2026-09-22T00:00:01.120Z',ai_latency_ms:1000,task_field_key:'design_note',task_field_label:'用一句话说明你的设计思路',task_field_stage:'before_update',task_context:{field_key:'design_note'}});
const msgs=await researchService.getMessages('S01','W1'); if(!msgs[0]?.message_has_image||msgs[0]?.attachments?.length!==1) throw new Error('image message metadata missing');
if(msgs[0]?.interaction_id!=='smoke-i1'||msgs[0]?.ai_latency_ms!==1000||msgs[0]?.task_field_key!=='design_note') throw new Error('interaction timing/task-step metadata missing');
await researchService.saveFields('S01','W2',{core_problem:'排队与信息判断'},{reason:'smoke_revision',last_ai_message_id:'ai-smoke',last_ai_message_at:new Date().toISOString()});
const revs=await researchService.getRevisions('S01','W2'); if(!revs.length||!revs[0].field_label||!('field_stage' in revs[0])) throw new Error('revision field label/stage missing');
if(getSessionConfig('W2').chat_image_enabled!==false) throw new Error('W2 chat image must be disabled');
await researchService.setParticipantMeta('S01',{condition:'A'});
if(aiVariantFor({session:getSessionConfig('W4'),condition:'A',isTest:false})!=='supported') throw new Error('A routing failed');
if(aiVariantFor({session:getSessionConfig('W4'),condition:'B',isTest:false})!=='free') throw new Error('B routing failed');
if(aiVariantFor({session:getSessionConfig('W10'),condition:'A',isTest:false})!=='free') throw new Error('transfer routing failed');
const mm=cozeService.buildAdditionalMessage('看看这张图',{fileId:'112233'});
if(mm.content_type!=='object_string'||!mm.content.includes('image')) throw new Error('multimodal Coze message failed');
const reset=await researchService.archiveAndResetSession('S01','W1',{reason:'smoke_reset'});
if(!reset.archived_previous) throw new Error('reset archive missing');
r=await researchService.getSessionRecord('S01','W1');
if(r.started_at||r.ai_used||Object.keys(r.artifacts||{}).length) throw new Error('session reset failed');
const archives=await researchService.listResetArchives();
if(!archives.length) throw new Error('reset archive list missing');
const restoreTarget=archives.find(x=>x.data?.participant?.participant_id==='S01'&&x.data?.session_config?.id==='W1');
if(!restoreTarget) throw new Error('restorable archive missing');
const restored=await researchService.restoreResetArchive(restoreTarget.key);
if(!restored.restored) throw new Error('reset archive restore failed');
r=await researchService.getSessionRecord('S01','W1');
if(!r.started_at) throw new Error('restored session record missing');
await researchService.archiveAndResetSession('S01','W1',{reason:'smoke_reset_again'});

// Service-level whole-cohort replacement still exists for exceptional maintenance, but the HTTP route is disabled by default in v11.23.
await researchService.ensureStarted('S01','W2');
await storageService.putObject('uploads/S01/W2/design_sketch/old.jpg', Buffer.from('old'));
await researchService.createParticipant('S00',{grade:'',condition:'unassigned'});
await researchService.ensureStarted('S00','W1');
const beforeSettings=await researchService.getSettings();
const replacementRows=Array.from({length:30},(_,i)=>({participant_id:`S${String(i+1).padStart(2,'0')}`,login_name:`新学生${String(i+1).padStart(2,'0')}`,grade:i<10?'6':i<20?'7':'8',condition:'unassigned'}));
const replaced=await researchService.replaceFormalCohort(replacementRows);
if(replaced.imported_count!==30||replaced.session_open!==false||replaced.cohort_revision===beforeSettings.cohort_revision) throw new Error('cohort replacement result invalid');
const s01w2=await researchService.getSessionRecord('S01','W2');
if(s01w2.started_at||s01w2.saved_at||Object.keys(s01w2.artifacts||{}).length) throw new Error('formal cohort active session data not cleared');
if(await storageService.getObjectBuffer('uploads/S01/W2/design_sketch/old.jpg')) throw new Error('formal cohort upload not cleared');
const s00w1=await researchService.getSessionRecord('S00','W1');
if(!s00w1.started_at) throw new Error('S00 should be preserved during cohort replacement');
const newP1=await researchService.getParticipant('S01');
if(newP1.grade!=='6'||!newP1.login_name_hash||newP1.condition!=='unassigned') throw new Error('new cohort roster meta missing');
console.log('SMOKE OK v11.23: roster/name safety + interaction metadata + revision history + safe reset/restore + exceptional cohort service path.');

