import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import authRoutes from '../../src/routes/auth.js';
import courseRoutes from '../../src/routes/course.js';
import chatRoutes from '../../src/routes/chat.js';
import uploadRoutes from '../../src/routes/upload.js';
import adminRoutes from '../../src/routes/admin.js';
import { securityMiddleware } from '../../src/middleware/security.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const app = express();
app.use(securityMiddleware);
app.use(express.json({ limit: '12mb' }));
app.use(express.urlencoded({ extended: true, limit: '12mb' }));
app.use(cookieParser());
app.use(express.static(join(__dirname, '../../../public')));
app.get('/health', (req, res) => res.json({ ok: true, version: 'course-v11.6' }));
app.use('/api', authRoutes);
app.use('/api', courseRoutes);
app.use('/api', chatRoutes);
app.use('/api', uploadRoutes);
app.use('/api/admin', adminRoutes);
app.use((req, res) => res.status(404).json({ error: 'Not found' }));
app.use((error, req, res, next) => { console.error('Unhandled error', error); res.status(500).json({ error: '服务器内部错误，请稍后重试。' }); });
export default app;
